services:
  - type: web
    name: mediaverse-api-backend
    env: php
    rootDir: MediaVerse
    buildCommand: composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.kzejqzrgcouoqpkxfjft.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        sync: false
      - key: TMDB_API_KEY
        sync: false
      - key: TMDB_ACCESS_TOKEN
        sync: false
      - key: IGDB_CLIENT_ID
        sync: false
      - key: IGDB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        value: https://mediaverse131.vercel.app
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GOOGLE_REDIRECT_URI
        value: https://mediaverse-api-backend.onrender.com/api/auth/google/callback
